Repository kyma-project/terraform-btp-kyma-environment, pull requests merged in 2024-09, with the labels that each got.

#6 First commit
  .reuse/dep5
  README.md
  docs/README.md
  docs/contributor/README.md
  docs/user/README.md
  docs/user/_sidebar.md
  main.tf
  output.tf
  provider.tf
  variables.tf
Labels: cla: yes, size/L

#8 change input var defaults
  examples/kyma-on-btp-basic/README.md
  examples/kyma-on-btp-basic/local-template.tfvars
  examples/kyma-on-btp-basic/variables.tf
Labels: cla: yes, size/S

#10 first pr CI job
  .github/workflows/pull-e2e-test.yml
  examples/kyma-on-btp-basic/variables.tf
  variables.tf
Labels: cla: yes, size/M

#11 explain prerequisites
  .github/workflows/pull-e2e-test.yml
  examples/kyma-on-btp-basic/README.md
Labels: cla: yes, size/S

#12 sha
  .github/workflows/pull-e2e-test.yml
Labels: cla: yes, size/XS

#13 Add dependabot
  .github/dependabot.yml
Labels: cla: yes, lgtm, size/S

#17 module list configurable
  examples/kyma-on-btp-new-sa/main.tf
  examples/kyma-on-btp-new-sa/variables.tf
  main.tf
  variables.tf
Labels: cla: yes, size/M

#16 Update reuse info
  .reuse/dep5
  README.md
  REUSE.toml
Labels: size/M

#18 Bump sap/btp provider
  examples/kyma-on-btp-new-sa/main.tf
  examples/kyma-on-btp-reuse-sa/main.tf
  provider.tf
Labels: cla: yes

#21 Add basic codeowners file
  CODEOWNERS
Labels: cla: yes, lgtm, size/M

#22 Make test run on PR
  .github/workflows/push-e2e-test.yml
Labels: cla: yes, lgtm, size/XS

#24 Disable e2e test on PR
  .github/workflows/push-e2e-test.yml
Labels: cla: yes, size/XS

#20 Update all terraform paths in one PR
  .github/dependabot.yml
Labels: cla: yes, size/XS

#26 change defaults
  examples/kyma-on-btp-new-sa/main.tf
  variables.tf
Labels: cla: yes, lgtm, size/S

#28 remove unneded dependency
  main.tf
Labels: cla: yes, size/XS
